#Main Configs
baseurl: https://joyslog.top
url: https://joyslog.top
assets_base_url: https://joyslog.top
date_format: "ordinal"
title: Joy's Blog
author: Joy

#RSS/Email
subscribe_rss: /feed.xml
email: marcustonytxi@gmail.com
repository: Xiao-La/xiao-la.github.io

#Jekyll Config
markdown: kramdown
kramdown:
    input: GFM
paginate: 15
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
plugins: [jekyll-paginate]
collections:
    study:
        output: true
        permalink: /study/:path/


#Cdn Config
cdn:
     jsdelivr:
         enabled: false

future: true