# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://xiao-la.tk
date_format: "ordinal"
title: BLOG | Xiao_La的个人网站
author: Xiao_La

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email: marcustonytxi@gmail.com

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours

# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: xiao-la
    repo: xiao-la.github.io
    oauth:
        client_id: f274da889848fa5e330e
        client_secret: 49eea8a3f3191b404d6ca3261bc404392fdfd3a4

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
